### 1. server info
id: 57bc97b7-50d2-4d87-a0bf-511221ca468c    # device ID
ip: 192.168.10.50    # device IP address

### 2. filestore info
performance: 0    # device performance: 1 for "high", or 0 for "low"

### 3. file-sharing info
fs_protocol: davfs  # protocol name (WebDav is "davfs")
fs_directory: "/"   # the directory of target files for mounting
fs_port: 10980    # file_sharing port
fs_user: kb109    # user
fs_pwd: 123456    # password