# Docker Version
# version: "3.8"

services:
  registry:
    image: registry:2
    ports:
    - "10960:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./storage:/data
  
  depository:
    build:
      context: ./daemon
    image: depository
    environment:
      - TZ=Asia/Shanghai
    entrypoint: python main.py