### 1. server info
id: 57bc97b7-50d2-4d87-a0bf-511221ca468c    # device ID
ip: 192.168.10.50    # device IP address

### 2. depository info
performance: 0    # device performance: 1 for "high", or 0 for "low"

### 3. registry info
reg_port: 10988    # registry port